const PALETTES=[
 {id:'pastel',accent:'#8fa6e8',colors:['#f28ba8','#f6a96b','#f2d06b','#a8d5a2','#7fc8a9','#8ec9e8','#8fa6e8','#b49be0','#e0a0c8','#c9a88a','#9aa7b4']},
 {id:'sunset',accent:'#f2825c',colors:['#e8615a','#f2825c','#f5a65b','#f2c57c','#d96c8f','#a85c9e','#7c6baf','#5f86c7','#c9705f','#e0a96d','#8e6f9e']},
 {id:'ocean',accent:'#4fa3d1',colors:['#4fa3d1','#62c4c1','#7fd1a6','#a7d8f0','#3e7cb1','#5b8fa8','#86baa5','#b9d9e8','#4e8098','#78a2cc','#9cc7c2']},
 {id:'candy',accent:'#ff6f91',colors:['#ff6f91','#ff9671','#ffc75f','#a0e7a5','#6bcb77','#4d96ff','#9b72f2','#ff7fb5','#ffd93d','#6ee7db','#c4a1ff']},
 {id:'bloom',accent:'#e27396',colors:['#e27396','#e8a87c','#d4c36a','#8fbc8f','#6b9080','#a26769','#c38d9e','#85a9c4','#d2b48c','#9c6644','#b5c99a']}
];
const TIERS=['all','beginner','easy','medium','hard','expert','master'];
const $=s=>document.querySelector(s), clone=x=>x.map(b=>[...b]);
let levels=[],level=null,state=[],moves=0,selected=-1,variant=0,history=[],activeTier='all',busy=false;
let sound=localStorage.getItem('cz-sound')!=='off',paletteIndex=+(localStorage.getItem('cz-palette')||0)%PALETTES.length;
let completed=JSON.parse(localStorage.getItem('cz-completed')||'{}');
const audio={};['click','select','pour','bubble','complete','hint'].forEach(n=>audio[n]=new Audio(`assets/sfx_${n}.wav`));
function play(name,volume=1){if(!sound)return;const a=audio[name];a.volume=volume;a.currentTime=0;a.play().catch(()=>{});}
function applyPalette(){const p=PALETTES[paletteIndex];document.documentElement.style.setProperty('--accent',p.accent);document.documentElement.style.setProperty('--accent-soft',p.accent+'26');document.documentElement.style.setProperty('--palette-1',p.colors[0]);document.documentElement.style.setProperty('--palette-2',p.colors[1]);document.documentElement.style.setProperty('--palette-3',p.colors[2]);localStorage.setItem('cz-palette',paletteIndex);}
function parseLevel(l,v=0){const flat=l.variants[v],out=[];for(let b=0;b<l.bottles;b++)out.push(flat.slice(b*4,b*4+4).filter(Boolean));return out;}
function topRun(b){if(!b.length)return[0,0];const c=b.at(-1);let n=0;for(let i=b.length-1;i>=0&&b[i]===c;i--)n++;return[c,n];}
function pourCount(from,to){if(from===to||!state[from]?.length||state[to].length>=4)return 0;const[c,n]=topRun(state[from]);if(state[to].length&&state[to].at(-1)!==c)return 0;return Math.min(n,4-state[to].length);}
function isBottleDone(b){return !b.length||(b.length===4&&b.every(c=>c===b[0]));}function solved(){return state.every(isBottleDone);}
function completedCount(){return state.filter(b=>b.length===4&&b.every(c=>c===b[0])).length;}
function save(){if(!level)return;localStorage.setItem('cz-current',level.n);localStorage.setItem('cz-game',JSON.stringify({n:level.n,state,moves,variant}));}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.remove('hidden');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.add('hidden'),1800);}
function renderLevels(){const filtered=levels.filter(l=>activeTier==='all'||l.t===activeTier);$('#levelGrid').innerHTML=filtered.map(l=>`<button class="level ${completed[l.n]?'done':''} ${level?.n===l.n?'current':''}" data-level="${l.n}">${l.n}${completed[l.n]?`<small>${'★'.repeat(completed[l.n].stars)}</small>`:''}</button>`).join('');$('#progressText').textContent=`${Object.keys(completed).length} complete`;$('#tierTabs').innerHTML=TIERS.map(t=>`<button class="${t===activeTier?'active':''}" data-tier="${t}">${t}</button>`).join('');}
function showLevels(){save();$('#gameScreen').classList.add('hidden');$('#levelScreen').classList.remove('hidden');$('#completeModal').classList.add('hidden');renderLevels();}
function loadLevel(number,resume=true){level=levels.find(l=>l.n===number)||levels[0];variant=0;moves=0;history=[];selected=-1;const saved=resume?JSON.parse(localStorage.getItem('cz-game')||'null'):null;if(saved?.n===level.n&&Array.isArray(saved.state)&&saved.state.length===level.bottles){state=clone(saved.state);moves=saved.moves||0;variant=saved.variant||0}else state=parseLevel(level,0);$('#levelScreen').classList.add('hidden');$('#gameScreen').classList.remove('hidden');$('#completeModal').classList.add('hidden');renderBoard();save();}
function renderBoard(){const p=PALETTES[paletteIndex];$('#levelNumber').textContent=level.n;$('#tierLabel').textContent=level.t;$('#moveCount').textContent=moves;$('#parCount').textContent=level.par;$('#gameProgressFill').style.width=`${completedCount()/level.colors*100}%`;$('#undoButton').disabled=!history.length||busy;$('#board').innerHTML=state.map((b,i)=>`<button class="bottle ${selected===i?'selected':''} ${isBottleDone(b)&&b.length?'complete':''}" data-bottle="${i}" aria-label="Bottle ${i+1}, ${b.length?b.length+' color segments':'empty'}"><span class="glass">${b.map((c,s)=>`<i class="liquid ${s===b.length-1?'top':''}" style="--slot:${s};--liquid:${p.colors[c-1]}"></i>`).join('')}</span><span class="bottle-index">${i+1}</span></button>`).join('');$('#message').textContent=selected<0?'Choose a bottle, then choose where to pour.':'Now choose a matching color or an empty bottle.';}
function tapBottle(i){if(busy)return;if(selected<0){if(!state[i].length){play('click',.6);invalid(i);return;}selected=i;play('select');renderBoard();return;}if(selected===i){selected=-1;play('click');renderBoard();return;}const count=pourCount(selected,i);if(!count){play('click',.55);invalid(i);selected=state[i].length?i:-1;setTimeout(renderBoard,280);return;}history.push({state:clone(state),moves,variant});const from=selected;selected=-1;busy=true;play('pour');state[i].push(...state[from].splice(-count));moves++;renderBoard();setTimeout(()=>{busy=false;const done=isBottleDone(state[i])&&state[i].length;if(done)play('bubble');renderBoard();save();if(solved())finish();},330);}
function invalid(i){const b=document.querySelector(`[data-bottle="${i}"]`);b?.classList.add('invalid');$('#message').textContent='That pour is not possible.';setTimeout(()=>b?.classList.remove('invalid'),330);}
function finish(){play('complete');const ratio=moves/level.par,stars=ratio<=1.25?3:ratio<=1.75?2:1;const prev=completed[level.n];completed[level.n]={stars:Math.max(stars,prev?.stars||0),best:Math.min(moves,prev?.best||Infinity)};localStorage.setItem('cz-completed',JSON.stringify(completed));localStorage.removeItem('cz-game');$('#completeLevel').textContent=level.n;$('#completeMoves').textContent=moves;$('#stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#nextButton').innerHTML=level.n<levels.length?'Next level <span>→</span>':'Choose a level <span>→</span>';setTimeout(()=>$('#completeModal').classList.remove('hidden'),350);}
function restart(){history=[];moves=0;selected=-1;state=parseLevel(level,variant);play('click');renderBoard();save();}
function shuffle(){history.push({state:clone(state),moves,variant});variant=(variant+1)%level.variants.length;state=parseLevel(level,variant);moves++;selected=-1;play('select');renderBoard();save();showToast(`Variant ${variant+1} of ${level.variants.length}`);}
function undo(){const h=history.pop();if(!h)return;state=h.state;moves=h.moves;variant=h.variant;selected=-1;play('click');renderBoard();save();}
document.addEventListener('click',e=>{const bottle=e.target.closest('[data-bottle]'),lvl=e.target.closest('[data-level]'),tier=e.target.closest('[data-tier]');if(bottle)tapBottle(+bottle.dataset.bottle);if(lvl)loadLevel(+lvl.dataset.level,false);if(tier){activeTier=tier.dataset.tier;renderLevels();}});
$('#homeButton').onclick=$('#backButton').onclick=showLevels;$('#undoButton').onclick=undo;$('#restartButton').onclick=restart;$('#shuffleButton').onclick=shuffle;$('#continueButton').onclick=()=>loadLevel(+(localStorage.getItem('cz-current')||1));$('#replayButton').onclick=()=>{restart();$('#completeModal').classList.add('hidden')};$('#nextButton').onclick=()=>level.n<levels.length?loadLevel(level.n+1,false):showLevels();
$('#soundButton').onclick=()=>{sound=!sound;localStorage.setItem('cz-sound',sound?'on':'off');$('#soundButton').textContent=sound?'♫':'♩';if(sound)play('select')};$('#paletteButton').onclick=()=>{paletteIndex=(paletteIndex+1)%PALETTES.length;applyPalette();play('hint');if(level)renderBoard();showToast(`${PALETTES[paletteIndex].id[0].toUpperCase()+PALETTES[paletteIndex].id.slice(1)} palette`)};
applyPalette();$('#soundButton').textContent=sound?'♫':'♩';fetch('assets/levels.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(data=>{levels=data.levels;renderLevels();const current=+(localStorage.getItem('cz-current')||1);$('#continueButton').innerHTML=`${current>1?'Continue level '+current:'Begin with level 1'} <span>→</span>`}).catch(()=>{$('#levelGrid').innerHTML='<p>Levels could not be loaded. Please refresh.</p>'});
